In [1]:
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from streamlit_folium import folium_static
import folium

In [11]:
data_url=('C:\\Users\\dell\\crimeproject\\crime_data_1.csv')
data=pd.read_csv(data_url)
data

,STATE/UT,DISTRICT,ARSON,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,DACOITY,ATTEMPT TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,Latitude(Degree NORTH),longitude (Degree EAST),TOTAL IPC CRIMES,YEAR,MURDER
0,DELHI UT,EAST,4,15,4,51,24,0,24,163,...,11,27,0,23,1552,28.6280,77.295600,4447,2001,56
1,DELHI UT,GRP(RLY),0,0,1,4,1,0,1,7,...,0,0,0,0,129,28.6448,77.216721,1630,2001,11
2,DELHI UT,IGI AIRPORT,1,1,0,2,0,0,0,4,...,2,0,0,2,61,28.5562,77.100000,625,2001,2
3,DELHI UT,NEW DELHI,3,0,1,14,9,0,9,27,...,6,2,0,109,731,28.6139,77.209000,2660,2001,11
4,DELHI UT,NORTH,3,5,2,33,28,0,28,99,...,6,9,0,0,1729,28.7886,77.141200,3998,2001,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,Delhi UT,SOUTH WEST,10,5,23,88,68,234,0,0,...,488,425,4632,1492,3140,28.5929,77.034600,0,2014,66
184,Delhi UT,OUTER,0,0,0,1,0,0,0,0,...,0,0,1,0,1,28.5982,76.989900,0,2014,0
185,Delhi UT,OUTER,0,0,0,0,0,0,0,0,...,0,0,0,0,0,28.5982,76.989900,0,2014,0
186,Delhi UT,OUTER,0,0,0,0,0,0,0,0,...,0,0,0,0,0,28.5982,76.989900,0,2014,0
187,Delhi UT,WEST,5,6,27,77,101,251,0,0,...,709,263,9404,3351,6053,28.6663,77.068000,0,2014,55

In [12]:
st.title("Crime Insights of Delhi")
st.markdown("This application exploits Data analytics techniques to give useful insights to people so that they can be safe and have information about unknown areas they have to visit..")

In [13]:
!streamlit run app.py

Usage: streamlit run [OPTIONS] TARGET [ARGS]...

Error: Invalid value: File does not exist: app.py